### ISSUE TITLE
Tasks from Sprint Backlog WE 3/16

### ISSUE THREAD

**Issue by sabu2k18** [dhsynergetech/kmt#11]
- [x] Fix app version # shown on Home Page
- [x] Remove ID cols from Categories listing
- [x] Show Engine status in brackets when viewing station
- [ ] Fix deploy script for PCF
- [x] Display scorecard on home page
- [x] Rename entities to Categories
- [x] Add Review column to Article (Outstanding, Good, Poor)
- [x] Send email to Captain role when article is created or updated
- [x] Change icons in the Categories tab to match Stations, Engines & Articles

**Comment by brendondelong** [comment]
Key tasks completed!
